22:16:01 DEBUG : Logs will be stored at '/home/sean/Downloads/git/ECE385_FP/VID_OE1/workspace/IDE.log'.
22:16:03 INFO  : Launching XSCT server: xsct -n  -interactive /home/sean/Downloads/git/ECE385_FP/VID_OE1/workspace/temp_xsdb_launch_script.tcl
22:16:03 ERROR : (XSDB Server)which: no xlsclients in (/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_le/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_be/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/arm/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-none/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-linux/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/armr5/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/cmake-3.21.4/bin::/alottadata/tools/Xilinx/Vivado/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vivado/2022.2/ids_lite/ISE/bin/lin64:/alottadata/tools/Xilinx/Vitis/2022.2/aietools/bin:/alottadata/tools/Xilinx/Vivado/2022.2/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib/python3.8/site-packages::/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vitis_HLS/2022.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/18/bin)

22:16:03 INFO  : Platform repository initialization has completed.
22:16:03 INFO  : Registering command handlers for Vitis TCF services
22:19:03 ERROR : Timed out. 180 seconds have elapsed while waiting for XSCT server to launch.
22:19:03 INFO  : Launching XSCT server: xsct -n  -interactive /home/sean/Downloads/git/ECE385_FP/VID_OE1/workspace/temp_xsdb_launch_script.tcl
22:19:03 ERROR : Failed to call init_repo
Reason: xsct server communication channel is not established.
22:19:03 ERROR : Exception raised in executing the command =Failed to call init_repo
Reason: xsct server communication channel is not established. 
22:19:03 ERROR : (XSDB Server)which: no xlsclients in (/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_le/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_be/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/arm/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-none/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-linux/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/armr5/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/cmake-3.21.4/bin::/alottadata/tools/Xilinx/Vivado/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vivado/2022.2/ids_lite/ISE/bin/lin64:/alottadata/tools/Xilinx/Vitis/2022.2/aietools/bin:/alottadata/tools/Xilinx/Vivado/2022.2/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib/python3.8/site-packages::/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vitis_HLS/2022.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/18/bin)

22:22:03 ERROR : Timed out. 180 seconds have elapsed while waiting for XSCT server to launch.
22:22:03 ERROR : Failed to openhw "/tmp/hwspec_mb_ddr3_top4798191070078260076/mb_ddr3_top.xsa"
Reason: xsct server communication channel is not established.
22:22:03 INFO  : Launching XSCT server: xsct -n  -interactive /home/sean/Downloads/git/ECE385_FP/VID_OE1/workspace/temp_xsdb_launch_script.tcl
22:22:03 ERROR : (XSDB Server)which: no xlsclients in (/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_le/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_be/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/arm/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-none/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-linux/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/armr5/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/cmake-3.21.4/bin::/alottadata/tools/Xilinx/Vivado/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vivado/2022.2/ids_lite/ISE/bin/lin64:/alottadata/tools/Xilinx/Vitis/2022.2/aietools/bin:/alottadata/tools/Xilinx/Vivado/2022.2/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib/python3.8/site-packages::/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vitis_HLS/2022.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/18/bin)

22:25:03 ERROR : Timed out. 180 seconds have elapsed while waiting for XSCT server to launch.
22:25:03 ERROR : xsct server communication channel is not established.
22:25:03 INFO  : Launching XSCT server: xsct -n  -interactive /home/sean/Downloads/git/ECE385_FP/VID_OE1/workspace/temp_xsdb_launch_script.tcl
22:25:03 ERROR : (XSDB Server)which: no xlsclients in (/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_le/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_be/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/arm/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-none/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-linux/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/armr5/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/cmake-3.21.4/bin::/alottadata/tools/Xilinx/Vivado/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vivado/2022.2/ids_lite/ISE/bin/lin64:/alottadata/tools/Xilinx/Vitis/2022.2/aietools/bin:/alottadata/tools/Xilinx/Vivado/2022.2/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib/python3.8/site-packages::/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vitis_HLS/2022.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/18/bin)

22:28:03 ERROR : Timed out. 180 seconds have elapsed while waiting for XSCT server to launch.
22:28:03 INFO  : Launching XSCT server: xsct -n  -interactive /home/sean/Downloads/git/ECE385_FP/VID_OE1/workspace/temp_xsdb_launch_script.tcl
22:28:03 ERROR : (XSDB Server)which: no xlsclients in (/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_le/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_be/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/arm/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-none/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-linux/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/armr5/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/cmake-3.21.4/bin::/alottadata/tools/Xilinx/Vivado/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vivado/2022.2/ids_lite/ISE/bin/lin64:/alottadata/tools/Xilinx/Vitis/2022.2/aietools/bin:/alottadata/tools/Xilinx/Vivado/2022.2/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib/python3.8/site-packages::/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vitis_HLS/2022.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/18/bin)

22:31:03 ERROR : Timed out. 180 seconds have elapsed while waiting for XSCT server to launch.
22:31:03 INFO  : Launching XSCT server: xsct -n  -interactive /home/sean/Downloads/git/ECE385_FP/VID_OE1/workspace/temp_xsdb_launch_script.tcl
22:31:03 ERROR : Failed to openhw "/tmp/hwspec_mb_ddr3_top4798191070078260076/mb_ddr3_top.xsa"
Reason: xsct server communication channel is not established.
22:31:03 ERROR : (XSDB Server)which: no xlsclients in (/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_le/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_be/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/arm/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-none/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-linux/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/armr5/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/cmake-3.21.4/bin::/alottadata/tools/Xilinx/Vivado/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vivado/2022.2/ids_lite/ISE/bin/lin64:/alottadata/tools/Xilinx/Vitis/2022.2/aietools/bin:/alottadata/tools/Xilinx/Vivado/2022.2/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib/python3.8/site-packages::/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vitis_HLS/2022.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/18/bin)

22:34:03 ERROR : Timed out. 180 seconds have elapsed while waiting for XSCT server to launch.
22:34:03 INFO  : Launching XSCT server: xsct -n  -interactive /home/sean/Downloads/git/ECE385_FP/VID_OE1/workspace/temp_xsdb_launch_script.tcl
22:34:03 ERROR : Failed to query RDI_DATADIR
Reason: xsct server communication channel is not established.
22:34:03 ERROR : Exception raised in executing the command =Failed to query RDI_DATADIR
Reason: xsct server communication channel is not established. 
22:34:03 ERROR : (XSDB Server)which: no xlsclients in (/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_le/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_be/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/arm/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-none/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-linux/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/armr5/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/cmake-3.21.4/bin::/alottadata/tools/Xilinx/Vivado/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vivado/2022.2/ids_lite/ISE/bin/lin64:/alottadata/tools/Xilinx/Vitis/2022.2/aietools/bin:/alottadata/tools/Xilinx/Vivado/2022.2/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib/python3.8/site-packages::/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vitis_HLS/2022.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/18/bin)

22:37:03 ERROR : Timed out. 180 seconds have elapsed while waiting for XSCT server to launch.
22:37:03 ERROR : Failed to openhw "/tmp/hwspec_mb_ddr3_top4798191070078260076/mb_ddr3_top.xsa"
Reason: xsct server communication channel is not established.
01:50:23 INFO  : Launching XSCT server: xsct -n  -interactive /home/sean/Downloads/git/ECE385_FP/VID_OE1/workspace/temp_xsdb_launch_script.tcl
01:50:23 ERROR : (XSDB Server)which: no xlsclients in (/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_le/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/microblaze/linux_toolchain/lin64_be/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/arm/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-none/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch64/lin/aarch64-linux/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/armr5/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/cmake-3.21.4/bin::/alottadata/tools/Xilinx/Vivado/2022.2/gnu/microblaze/lin/bin:/alottadata/tools/Xilinx/Vitis/2022.2/bin:/alottadata/tools/Xilinx/Vitis/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vivado/2022.2/ids_lite/ISE/bin/lin64:/alottadata/tools/Xilinx/Vitis/2022.2/aietools/bin:/alottadata/tools/Xilinx/Vivado/2022.2/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/bin:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib:/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/python-3.8.3/lib/python3.8/site-packages::/alottadata/tools/Xilinx/Vivado/2022.2/tps/lnx64/jre11.0.11_9/bin:/alottadata/tools/Xilinx/Vitis_HLS/2022.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/18/bin)

